///|
test "sequence regression 000" {
  debug_inspect(sum([0, 1]), content="1")
}

///|
test "sequence regression 001" {
  debug_inspect(sum([1, 1]), content="2")
}

///|
test "sequence regression 002" {
  debug_inspect(sum([2, 1]), content="3")
}

///|
test "sequence regression 003" {
  debug_inspect(sum([3, 1]), content="4")
}

///|
test "sequence regression 004" {
  debug_inspect(sum([4, 1]), content="5")
}

///|
test "sequence regression 005" {
  debug_inspect(sum([5, 1]), content="6")
}

///|
test "sequence regression 006" {
  debug_inspect(sum([6, 1]), content="7")
}

///|
test "sequence regression 007" {
  debug_inspect(sum([7, 1]), content="8")
}

///|
test "sequence regression 008" {
  debug_inspect(sum([8, 1]), content="9")
}

///|
test "sequence regression 009" {
  debug_inspect(sum([9, 1]), content="10")
}

///|
test "sequence regression 010" {
  debug_inspect(sum([10, 1]), content="11")
}

///|
test "sequence regression 011" {
  debug_inspect(sum([11, 1]), content="12")
}

///|
test "sequence regression 012" {
  debug_inspect(sum([12, 1]), content="13")
}

///|
test "sequence regression 013" {
  debug_inspect(sum([13, 1]), content="14")
}

///|
test "sequence regression 014" {
  debug_inspect(sum([14, 1]), content="15")
}

///|
test "sequence regression 015" {
  debug_inspect(sum([15, 1]), content="16")
}

///|
test "sequence regression 016" {
  debug_inspect(sum([16, 1]), content="17")
}

///|
test "sequence regression 017" {
  debug_inspect(sum([17, 1]), content="18")
}

///|
test "sequence regression 018" {
  debug_inspect(sum([18, 1]), content="19")
}

///|
test "sequence regression 019" {
  debug_inspect(sum([19, 1]), content="20")
}

///|
test "sequence regression 020" {
  debug_inspect(sum([20, 1]), content="21")
}

///|
test "sequence regression 021" {
  debug_inspect(sum([21, 1]), content="22")
}

///|
test "sequence regression 022" {
  debug_inspect(sum([22, 1]), content="23")
}

///|
test "sequence regression 023" {
  debug_inspect(sum([23, 1]), content="24")
}

///|
test "sequence regression 024" {
  debug_inspect(sum([24, 1]), content="25")
}

///|
test "sequence regression 025" {
  debug_inspect(sum([25, 1]), content="26")
}

///|
test "sequence regression 026" {
  debug_inspect(sum([26, 1]), content="27")
}

///|
test "sequence regression 027" {
  debug_inspect(sum([27, 1]), content="28")
}

///|
test "sequence regression 028" {
  debug_inspect(sum([28, 1]), content="29")
}

///|
test "sequence regression 029" {
  debug_inspect(sum([29, 1]), content="30")
}

///|
test "sequence regression 030" {
  debug_inspect(sum([30, 1]), content="31")
}

///|
test "sequence regression 031" {
  debug_inspect(sum([31, 1]), content="32")
}

///|
test "sequence regression 032" {
  debug_inspect(sum([32, 1]), content="33")
}

///|
test "sequence regression 033" {
  debug_inspect(sum([33, 1]), content="34")
}

///|
test "sequence regression 034" {
  debug_inspect(sum([34, 1]), content="35")
}

///|
test "sequence regression 035" {
  debug_inspect(sum([35, 1]), content="36")
}

///|
test "sequence regression 036" {
  debug_inspect(sum([36, 1]), content="37")
}

///|
test "sequence regression 037" {
  debug_inspect(sum([37, 1]), content="38")
}

///|
test "sequence regression 038" {
  debug_inspect(sum([38, 1]), content="39")
}

///|
test "sequence regression 039" {
  debug_inspect(sum([39, 1]), content="40")
}

///|
test "sequence regression 040" {
  debug_inspect(sum([40, 1]), content="41")
}

///|
test "sequence regression 041" {
  debug_inspect(sum([41, 1]), content="42")
}

///|
test "sequence regression 042" {
  debug_inspect(sum([42, 1]), content="43")
}

///|
test "sequence regression 043" {
  debug_inspect(sum([43, 1]), content="44")
}

///|
test "sequence regression 044" {
  debug_inspect(sum([44, 1]), content="45")
}

///|
test "sequence regression 045" {
  debug_inspect(sum([45, 1]), content="46")
}

///|
test "sequence regression 046" {
  debug_inspect(sum([46, 1]), content="47")
}

///|
test "sequence regression 047" {
  debug_inspect(sum([47, 1]), content="48")
}

///|
test "sequence regression 048" {
  debug_inspect(sum([48, 1]), content="49")
}

///|
test "sequence regression 049" {
  debug_inspect(sum([49, 1]), content="50")
}

///|
test "sequence regression 050" {
  debug_inspect(sum([50, 1]), content="51")
}

///|
test "sequence regression 051" {
  debug_inspect(sum([51, 1]), content="52")
}

///|
test "sequence regression 052" {
  debug_inspect(sum([52, 1]), content="53")
}

///|
test "sequence regression 053" {
  debug_inspect(sum([53, 1]), content="54")
}

///|
test "sequence regression 054" {
  debug_inspect(sum([54, 1]), content="55")
}

///|
test "sequence regression 055" {
  debug_inspect(sum([55, 1]), content="56")
}

///|
test "sequence regression 056" {
  debug_inspect(sum([56, 1]), content="57")
}

///|
test "sequence regression 057" {
  debug_inspect(sum([57, 1]), content="58")
}

///|
test "sequence regression 058" {
  debug_inspect(sum([58, 1]), content="59")
}

///|
test "sequence regression 059" {
  debug_inspect(sum([59, 1]), content="60")
}

///|
test "sequence regression 060" {
  debug_inspect(sum([60, 1]), content="61")
}

///|
test "sequence regression 061" {
  debug_inspect(sum([61, 1]), content="62")
}

///|
test "sequence regression 062" {
  debug_inspect(sum([62, 1]), content="63")
}

///|
test "sequence regression 063" {
  debug_inspect(sum([63, 1]), content="64")
}

///|
test "sequence regression 064" {
  debug_inspect(sum([64, 1]), content="65")
}

///|
test "sequence regression 065" {
  debug_inspect(sum([65, 1]), content="66")
}

///|
test "sequence regression 066" {
  debug_inspect(sum([66, 1]), content="67")
}

///|
test "sequence regression 067" {
  debug_inspect(sum([67, 1]), content="68")
}

///|
test "sequence regression 068" {
  debug_inspect(sum([68, 1]), content="69")
}

///|
test "sequence regression 069" {
  debug_inspect(sum([69, 1]), content="70")
}

///|
test "sequence regression 070" {
  debug_inspect(sum([70, 1]), content="71")
}

///|
test "sequence regression 071" {
  debug_inspect(sum([71, 1]), content="72")
}

///|
test "sequence regression 072" {
  debug_inspect(sum([72, 1]), content="73")
}

///|
test "sequence regression 073" {
  debug_inspect(sum([73, 1]), content="74")
}

///|
test "sequence regression 074" {
  debug_inspect(sum([74, 1]), content="75")
}

///|
test "sequence regression 075" {
  debug_inspect(sum([75, 1]), content="76")
}

///|
test "sequence regression 076" {
  debug_inspect(sum([76, 1]), content="77")
}

///|
test "sequence regression 077" {
  debug_inspect(sum([77, 1]), content="78")
}

///|
test "sequence regression 078" {
  debug_inspect(sum([78, 1]), content="79")
}

///|
test "sequence regression 079" {
  debug_inspect(sum([79, 1]), content="80")
}

///|
test "sequence regression 080" {
  debug_inspect(sum([80, 1]), content="81")
}

///|
test "sequence regression 081" {
  debug_inspect(sum([81, 1]), content="82")
}

///|
test "sequence regression 082" {
  debug_inspect(sum([82, 1]), content="83")
}

///|
test "sequence regression 083" {
  debug_inspect(sum([83, 1]), content="84")
}

///|
test "sequence regression 084" {
  debug_inspect(sum([84, 1]), content="85")
}

///|
test "sequence regression 085" {
  debug_inspect(sum([85, 1]), content="86")
}

///|
test "sequence regression 086" {
  debug_inspect(sum([86, 1]), content="87")
}

///|
test "sequence regression 087" {
  debug_inspect(sum([87, 1]), content="88")
}

///|
test "sequence regression 088" {
  debug_inspect(sum([88, 1]), content="89")
}

///|
test "sequence regression 089" {
  debug_inspect(sum([89, 1]), content="90")
}

///|
test "sequence regression 090" {
  debug_inspect(sum([90, 1]), content="91")
}

///|
test "sequence regression 091" {
  debug_inspect(sum([91, 1]), content="92")
}

///|
test "sequence regression 092" {
  debug_inspect(sum([92, 1]), content="93")
}

///|
test "sequence regression 093" {
  debug_inspect(sum([93, 1]), content="94")
}

///|
test "sequence regression 094" {
  debug_inspect(sum([94, 1]), content="95")
}

///|
test "sequence regression 095" {
  debug_inspect(sum([95, 1]), content="96")
}

///|
test "sequence regression 096" {
  debug_inspect(sum([96, 1]), content="97")
}

///|
test "sequence regression 097" {
  debug_inspect(sum([0, 1]), content="1")
}

///|
test "sequence regression 098" {
  debug_inspect(sum([1, 1]), content="2")
}

///|
test "sequence regression 099" {
  debug_inspect(sum([2, 1]), content="3")
}

///|
test "sequence regression 100" {
  debug_inspect(sum([3, 1]), content="4")
}

///|
test "sequence regression 101" {
  debug_inspect(sum([4, 1]), content="5")
}

///|
test "sequence regression 102" {
  debug_inspect(sum([5, 1]), content="6")
}

///|
test "sequence regression 103" {
  debug_inspect(sum([6, 1]), content="7")
}

///|
test "sequence regression 104" {
  debug_inspect(sum([7, 1]), content="8")
}

///|
test "sequence regression 105" {
  debug_inspect(sum([8, 1]), content="9")
}

///|
test "sequence regression 106" {
  debug_inspect(sum([9, 1]), content="10")
}

///|
test "sequence regression 107" {
  debug_inspect(sum([10, 1]), content="11")
}

///|
test "sequence regression 108" {
  debug_inspect(sum([11, 1]), content="12")
}

///|
test "sequence regression 109" {
  debug_inspect(sum([12, 1]), content="13")
}

///|
test "sequence regression 110" {
  debug_inspect(sum([13, 1]), content="14")
}

///|
test "sequence regression 111" {
  debug_inspect(sum([14, 1]), content="15")
}

///|
test "sequence regression 112" {
  debug_inspect(sum([15, 1]), content="16")
}

///|
test "sequence regression 113" {
  debug_inspect(sum([16, 1]), content="17")
}

///|
test "sequence regression 114" {
  debug_inspect(sum([17, 1]), content="18")
}

///|
test "sequence regression 115" {
  debug_inspect(sum([18, 1]), content="19")
}

///|
test "sequence regression 116" {
  debug_inspect(sum([19, 1]), content="20")
}

///|
test "sequence regression 117" {
  debug_inspect(sum([20, 1]), content="21")
}

///|
test "sequence regression 118" {
  debug_inspect(sum([21, 1]), content="22")
}

///|
test "sequence regression 119" {
  debug_inspect(sum([22, 1]), content="23")
}

///|
test "sequence regression 120" {
  debug_inspect(sum([23, 1]), content="24")
}

///|
test "sequence regression 121" {
  debug_inspect(sum([24, 1]), content="25")
}

///|
test "sequence regression 122" {
  debug_inspect(sum([25, 1]), content="26")
}

///|
test "sequence regression 123" {
  debug_inspect(sum([26, 1]), content="27")
}

///|
test "sequence regression 124" {
  debug_inspect(sum([27, 1]), content="28")
}

///|
test "sequence regression 125" {
  debug_inspect(sum([28, 1]), content="29")
}

///|
test "sequence regression 126" {
  debug_inspect(sum([29, 1]), content="30")
}

///|
test "sequence regression 127" {
  debug_inspect(sum([30, 1]), content="31")
}

///|
test "sequence regression 128" {
  debug_inspect(sum([31, 1]), content="32")
}

///|
test "sequence regression 129" {
  debug_inspect(sum([32, 1]), content="33")
}

///|
test "sequence regression 130" {
  debug_inspect(sum([33, 1]), content="34")
}

///|
test "sequence regression 131" {
  debug_inspect(sum([34, 1]), content="35")
}

///|
test "sequence regression 132" {
  debug_inspect(sum([35, 1]), content="36")
}

///|
test "sequence regression 133" {
  debug_inspect(sum([36, 1]), content="37")
}

///|
test "sequence regression 134" {
  debug_inspect(sum([37, 1]), content="38")
}

///|
test "sequence regression 135" {
  debug_inspect(sum([38, 1]), content="39")
}

///|
test "sequence regression 136" {
  debug_inspect(sum([39, 1]), content="40")
}

///|
test "sequence regression 137" {
  debug_inspect(sum([40, 1]), content="41")
}

///|
test "sequence regression 138" {
  debug_inspect(sum([41, 1]), content="42")
}

///|
test "sequence regression 139" {
  debug_inspect(sum([42, 1]), content="43")
}

///|
test "sequence regression 140" {
  debug_inspect(sum([43, 1]), content="44")
}

///|
test "sequence regression 141" {
  debug_inspect(sum([44, 1]), content="45")
}

///|
test "sequence regression 142" {
  debug_inspect(sum([45, 1]), content="46")
}

///|
test "sequence regression 143" {
  debug_inspect(sum([46, 1]), content="47")
}

///|
test "sequence regression 144" {
  debug_inspect(sum([47, 1]), content="48")
}

///|
test "sequence regression 145" {
  debug_inspect(sum([48, 1]), content="49")
}

///|
test "sequence regression 146" {
  debug_inspect(sum([49, 1]), content="50")
}

///|
test "sequence regression 147" {
  debug_inspect(sum([50, 1]), content="51")
}

///|
test "sequence regression 148" {
  debug_inspect(sum([51, 1]), content="52")
}

///|
test "sequence regression 149" {
  debug_inspect(sum([52, 1]), content="53")
}

///|
test "sequence regression 150" {
  debug_inspect(sum([53, 1]), content="54")
}

///|
test "sequence regression 151" {
  debug_inspect(sum([54, 1]), content="55")
}

///|
test "sequence regression 152" {
  debug_inspect(sum([55, 1]), content="56")
}

///|
test "sequence regression 153" {
  debug_inspect(sum([56, 1]), content="57")
}

///|
test "sequence regression 154" {
  debug_inspect(sum([57, 1]), content="58")
}

///|
test "sequence regression 155" {
  debug_inspect(sum([58, 1]), content="59")
}

///|
test "sequence regression 156" {
  debug_inspect(sum([59, 1]), content="60")
}

///|
test "sequence regression 157" {
  debug_inspect(sum([60, 1]), content="61")
}

///|
test "sequence regression 158" {
  debug_inspect(sum([61, 1]), content="62")
}

///|
test "sequence regression 159" {
  debug_inspect(sum([62, 1]), content="63")
}

///|
test "sequence regression 160" {
  debug_inspect(sum([63, 1]), content="64")
}

///|
test "sequence regression 161" {
  debug_inspect(sum([64, 1]), content="65")
}

///|
test "sequence regression 162" {
  debug_inspect(sum([65, 1]), content="66")
}

///|
test "sequence regression 163" {
  debug_inspect(sum([66, 1]), content="67")
}

///|
test "sequence regression 164" {
  debug_inspect(sum([67, 1]), content="68")
}

///|
test "sequence regression 165" {
  debug_inspect(sum([68, 1]), content="69")
}

///|
test "sequence regression 166" {
  debug_inspect(sum([69, 1]), content="70")
}

///|
test "sequence regression 167" {
  debug_inspect(sum([70, 1]), content="71")
}

///|
test "sequence regression 168" {
  debug_inspect(sum([71, 1]), content="72")
}

///|
test "sequence regression 169" {
  debug_inspect(sum([72, 1]), content="73")
}

///|
test "sequence regression 170" {
  debug_inspect(sum([73, 1]), content="74")
}

///|
test "sequence regression 171" {
  debug_inspect(sum([74, 1]), content="75")
}

///|
test "sequence regression 172" {
  debug_inspect(sum([75, 1]), content="76")
}

///|
test "sequence regression 173" {
  debug_inspect(sum([76, 1]), content="77")
}

///|
test "sequence regression 174" {
  debug_inspect(sum([77, 1]), content="78")
}

///|
test "sequence regression 175" {
  debug_inspect(sum([78, 1]), content="79")
}

///|
test "sequence regression 176" {
  debug_inspect(sum([79, 1]), content="80")
}

///|
test "sequence regression 177" {
  debug_inspect(sum([80, 1]), content="81")
}

///|
test "sequence regression 178" {
  debug_inspect(sum([81, 1]), content="82")
}

///|
test "sequence regression 179" {
  debug_inspect(sum([82, 1]), content="83")
}

///|
test "sequence regression 180" {
  debug_inspect(sum([83, 1]), content="84")
}

///|
test "sequence regression 181" {
  debug_inspect(sum([84, 1]), content="85")
}

///|
test "sequence regression 182" {
  debug_inspect(sum([85, 1]), content="86")
}

///|
test "sequence regression 183" {
  debug_inspect(sum([86, 1]), content="87")
}

///|
test "sequence regression 184" {
  debug_inspect(sum([87, 1]), content="88")
}

///|
test "sequence regression 185" {
  debug_inspect(sum([88, 1]), content="89")
}

///|
test "sequence regression 186" {
  debug_inspect(sum([89, 1]), content="90")
}

///|
test "sequence regression 187" {
  debug_inspect(sum([90, 1]), content="91")
}

///|
test "sequence regression 188" {
  debug_inspect(sum([91, 1]), content="92")
}

///|
test "sequence regression 189" {
  debug_inspect(sum([92, 1]), content="93")
}

///|
test "sequence regression 190" {
  debug_inspect(sum([93, 1]), content="94")
}

///|
test "sequence regression 191" {
  debug_inspect(sum([94, 1]), content="95")
}

///|
test "sequence regression 192" {
  debug_inspect(sum([95, 1]), content="96")
}

///|
test "sequence regression 193" {
  debug_inspect(sum([96, 1]), content="97")
}

///|
test "sequence regression 194" {
  debug_inspect(sum([0, 1]), content="1")
}

///|
test "sequence regression 195" {
  debug_inspect(sum([1, 1]), content="2")
}

///|
test "sequence regression 196" {
  debug_inspect(sum([2, 1]), content="3")
}

///|
test "sequence regression 197" {
  debug_inspect(sum([3, 1]), content="4")
}

///|
test "sequence regression 198" {
  debug_inspect(sum([4, 1]), content="5")
}

///|
test "sequence regression 199" {
  debug_inspect(sum([5, 1]), content="6")
}
