name: Publish Mooncake
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MoonBit
        shell: bash
        run: curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
      - name: Add MoonBit to PATH
        shell: bash
        run: echo "$HOME/.moon/bin" >> "$GITHUB_PATH"
      - run: moon check --deny-warn
      - run: moon test --deny-warn
      - run: moon package --list
      - run: moon publish
        env:
          MOONCAKES_TOKEN: ${{ secrets.MOONCAKES_TOKEN }}
